export interface ClassConfig {
  id: string;
  name: string;
  category: 'Pre-Primary' | 'Primary' | 'Middle' | 'Secondary' | 'Senior Secondary';
  availableSubjects: { code: string; name: string; type: 'Core' | 'Language' | 'Skill' | 'Co-Scholastic' }[];
}

export const ACADEMIC_CLASSES: ClassConfig[] = [
  {
    id: 'NURSERY',
    name: 'Nursery',
    category: 'Pre-Primary',
    availableSubjects: [
      { code: 'NUR-ENG', name: 'English Rhymes & Phonics', type: 'Core' },
      { code: 'NUR-HIN', name: 'Hindi Balgeet & Kahani', type: 'Core' },
      { code: 'NUR-NUM', name: 'Number Work & Shapes', type: 'Core' },
      { code: 'NUR-ART', name: 'Drawing, Coloring & Motor Skills', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'LKG',
    name: 'LKG (Lower Kindergarten)',
    category: 'Pre-Primary',
    availableSubjects: [
      { code: 'LKG-ENG', name: 'English Alphabet & Sight Words', type: 'Core' },
      { code: 'LKG-HIN', name: 'Hindi Akshar Gyan', type: 'Language' },
      { code: 'LKG-MAT', name: 'Mathematics (1-50 Counting)', type: 'Core' },
      { code: 'LKG-EVS', name: 'Environmental Awareness (EVS)', type: 'Core' },
      { code: 'LKG-ART', name: 'Art & Paper Craft', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'UKG',
    name: 'UKG (Upper Kindergarten)',
    category: 'Pre-Primary',
    availableSubjects: [
      { code: 'UKG-ENG', name: 'English Phonics & Simple Sentences', type: 'Core' },
      { code: 'UKG-HIN', name: 'Hindi Varnamala & Matras', type: 'Language' },
      { code: 'UKG-MAT', name: 'Mathematics (Addition/Subtraction Basics)', type: 'Core' },
      { code: 'UKG-EVS', name: 'General Science & Plants', type: 'Core' },
      { code: 'UKG-ART', name: 'Drawing, Painting & Origami', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'CLASS_1',
    name: 'Class 1',
    category: 'Primary',
    availableSubjects: [
      { code: '001', name: 'English (Marigold)', type: 'Core' },
      { code: '002', name: 'Hindi (Rimjhim)', type: 'Language' },
      { code: '041', name: 'Mathematics (Math-Magic)', type: 'Core' },
      { code: '086', name: 'Environmental Studies (EVS)', type: 'Core' },
      { code: '165', name: 'Computer Basics & Typing', type: 'Skill' },
      { code: '501', name: 'Art Education & Craft', type: 'Co-Scholastic' },
      { code: '502', name: 'Health & Physical Education (PEWB)', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'CLASS_6',
    name: 'Class 6',
    category: 'Middle',
    availableSubjects: [
      { code: '184', name: 'English (Honeycomb)', type: 'Core' },
      { code: '002', name: 'Hindi (Vasant)', type: 'Language' },
      { code: '122', name: 'Sanskrit (Ruchira)', type: 'Language' },
      { code: '041', name: 'Mathematics', type: 'Core' },
      { code: '086', name: 'General Science', type: 'Core' },
      { code: '087', name: 'Social Science (History/Civics/Geo)', type: 'Core' },
      { code: '402', name: 'Information Technology (Skill)', type: 'Skill' },
      { code: '417', name: 'Artificial Intelligence Foundations', type: 'Skill' },
      { code: '501', name: 'Art Education', type: 'Co-Scholastic' },
      { code: '502', name: 'PEWB & Sports', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'CLASS_9',
    name: 'Class 9',
    category: 'Secondary',
    availableSubjects: [
      { code: '184', name: 'English Language and Literature (Code 184)', type: 'Core' },
      { code: '101', name: 'English Communicative (Code 101)', type: 'Core' },
      { code: '002', name: 'Hindi Course A (Code 002)', type: 'Language' },
      { code: '085', name: 'Hindi Course B (Code 085)', type: 'Language' },
      { code: '122', name: 'Sanskrit (Code 122)', type: 'Language' },
      { code: '003', name: 'Urdu Course A/B', type: 'Language' },
      { code: '004', name: 'Punjabi (Code 004)', type: 'Language' },
      { code: '041', name: 'Mathematics Standard (Code 041)', type: 'Core' },
      { code: '241', name: 'Mathematics Basic (Code 241)', type: 'Core' },
      { code: '086', name: 'Science (Code 086)', type: 'Core' },
      { code: '087', name: 'Social Science (Code 087)', type: 'Core' },
      { code: '402', name: 'Information Technology (Code 402)', type: 'Skill' },
      { code: '417', name: 'Artificial Intelligence (Code 417)', type: 'Skill' },
      { code: '165', name: 'Computer Applications (Code 165)', type: 'Skill' },
      { code: '076', name: 'NCC (National Cadet Corps)', type: 'Skill' },
      { code: '501', name: 'Art Education', type: 'Co-Scholastic' },
      { code: '502', name: 'PEWB (Physical & Health Education)', type: 'Co-Scholastic' },
      { code: '503', name: 'Work Experience / SEWA', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'CLASS_10',
    name: 'Class 10 (Board)',
    category: 'Secondary',
    availableSubjects: [
      { code: '184', name: 'English Language and Literature (Code 184)', type: 'Core' },
      { code: '101', name: 'English Communicative (Code 101)', type: 'Core' },
      { code: '002', name: 'Hindi Course A (Code 002)', type: 'Language' },
      { code: '085', name: 'Hindi Course B (Code 085)', type: 'Language' },
      { code: '122', name: 'Sanskrit (Code 122)', type: 'Language' },
      { code: '003', name: 'Urdu', type: 'Language' },
      { code: '004', name: 'Punjabi', type: 'Language' },
      { code: '041', name: 'Mathematics Standard (Code 041)', type: 'Core' },
      { code: '241', name: 'Mathematics Basic (Code 241)', type: 'Core' },
      { code: '086', name: 'Science (Code 086)', type: 'Core' },
      { code: '087', name: 'Social Science (Code 087)', type: 'Core' },
      { code: '402', name: 'Information Technology (Code 402)', type: 'Skill' },
      { code: '417', name: 'Artificial Intelligence (Code 417)', type: 'Skill' },
      { code: '165', name: 'Computer Applications (Code 165)', type: 'Skill' },
      { code: '076', name: 'NCC', type: 'Skill' },
      { code: '501', name: 'Art Education', type: 'Co-Scholastic' },
      { code: '502', name: 'PEWB', type: 'Co-Scholastic' },
      { code: '503', name: 'Health & Physical Education', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'CLASS_11_SCI',
    name: 'Class 11 - Science',
    category: 'Senior Secondary',
    availableSubjects: [
      { code: '301', name: 'English Core (Code 301)', type: 'Core' },
      { code: '042', name: 'Physics (Code 042)', type: 'Core' },
      { code: '043', name: 'Chemistry (Code 043)', type: 'Core' },
      { code: '041', name: 'Mathematics (Code 041)', type: 'Core' },
      { code: '044', name: 'Biology (Code 044)', type: 'Core' },
      { code: '083', name: 'Computer Science (Code 083)', type: 'Skill' },
      { code: '065', name: 'Informatics Practices (Code 065)', type: 'Skill' },
      { code: '048', name: 'Physical Education (Code 048)', type: 'Skill' },
      { code: '500', name: 'General Studies & Health PE', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'CLASS_12_SCI',
    name: 'Class 12 - Science',
    category: 'Senior Secondary',
    availableSubjects: [
      { code: '301', name: 'English Core (Code 301)', type: 'Core' },
      { code: '042', name: 'Physics (Code 042)', type: 'Core' },
      { code: '043', name: 'Chemistry (Code 043)', type: 'Core' },
      { code: '041', name: 'Mathematics (Code 041)', type: 'Core' },
      { code: '044', name: 'Biology (Code 044)', type: 'Core' },
      { code: '083', name: 'Computer Science (Code 083)', type: 'Skill' },
      { code: '065', name: 'Informatics Practices (Code 065)', type: 'Skill' },
      { code: '048', name: 'Physical Education (Code 048)', type: 'Skill' },
      { code: '500', name: 'General Studies & Work Experience', type: 'Co-Scholastic' },
    ],
  },
  {
    id: 'CLASS_12_COM',
    name: 'Class 12 - Commerce',
    category: 'Senior Secondary',
    availableSubjects: [
      { code: '301', name: 'English Core (Code 301)', type: 'Core' },
      { code: '055', name: 'Accountancy (Code 055)', type: 'Core' },
      { code: '054', name: 'Business Studies (Code 054)', type: 'Core' },
      { code: '030', name: 'Economics (Code 030)', type: 'Core' },
      { code: '241', name: 'Applied Mathematics (Code 241)', type: 'Core' },
      { code: '065', name: 'Informatics Practices (Code 065)', type: 'Skill' },
      { code: '048', name: 'Physical Education (Code 048)', type: 'Skill' },
    ],
  },
  {
    id: 'CLASS_12_HUM',
    name: 'Class 12 - Humanities / Arts',
    category: 'Senior Secondary',
    availableSubjects: [
      { code: '301', name: 'English Core (Code 301)', type: 'Core' },
      { code: '027', name: 'History (Code 027)', type: 'Core' },
      { code: '028', name: 'Political Science (Code 028)', type: 'Core' },
      { code: '029', name: 'Geography (Code 029)', type: 'Core' },
      { code: '037', name: 'Psychology (Code 037)', type: 'Core' },
      { code: '030', name: 'Economics (Code 030)', type: 'Core' },
      { code: '048', name: 'Physical Education (Code 048)', type: 'Skill' },
    ],
  },
];
