export interface ClassConfig {
  id: string;
  name: string;
  availableSubjects: string[];
}

export const ACADEMIC_CLASSES: ClassConfig[] = [
  { id: 'NUR', name: 'Nursery', availableSubjects: ['English Rhymes & Phonics', 'Hindi Balgeet', 'Number Work & Shapes', 'Art & Coloring'] },
  { id: 'LKG', name: 'LKG', availableSubjects: ['English Sight Words', 'Hindi Akshar', 'Mathematics (1-50)', 'EVS Awareness', 'Art & Craft'] },
  { id: 'UKG', name: 'UKG', availableSubjects: ['English Sentences', 'Hindi Varnamala', 'Basic Math Addition', 'General Science', 'Art & Origami'] },
  { id: 'C1', name: 'Class 1', availableSubjects: ['English', 'Hindi', 'Mathematics', 'EVS', 'Computer Basics', 'Art Education'] },
  { id: 'C2', name: 'Class 2', availableSubjects: ['English', 'Hindi', 'Mathematics', 'EVS', 'Computer Basics', 'General Knowledge'] },
  { id: 'C3', name: 'Class 3', availableSubjects: ['English', 'Hindi', 'Mathematics', 'Science', 'Social Studies', 'Computer Studies'] },
  { id: 'C4', name: 'Class 4', availableSubjects: ['English', 'Hindi', 'Mathematics', 'Science', 'Social Studies', 'Computer / ICT'] },
  { id: 'C5', name: 'Class 5', availableSubjects: ['English', 'Hindi', 'Mathematics', 'General Science', 'Social Studies', 'Computer Science'] },
  { id: 'C6', name: 'Class 6', availableSubjects: ['English', 'Hindi', 'Sanskrit', 'Mathematics', 'Science', 'Social Science', 'Computer / Coding', 'AI Foundations'] },
  { id: 'C7', name: 'Class 7', availableSubjects: ['English', 'Hindi', 'Sanskrit', 'Mathematics', 'Science', 'Social Science', 'Computer / Coding', 'Robotics Basics'] },
  { id: 'C8', name: 'Class 8', availableSubjects: ['English', 'Hindi', 'Sanskrit', 'Mathematics', 'Science', 'Social Science', 'Computer Science', 'Artificial Intelligence'] },
  {
    id: 'C9',
    name: 'Class 9',
    availableSubjects: [
      'Mathematics Standard (Code 041)',
      'Mathematics Basic (Code 241)',
      'Science (Code 086)',
      'Social Science (Code 087)',
      'English Language and Literature (Code 184)',
      'English Communicative (Code 101)',
      'Hindi Course A (Code 002)',
      'Hindi Course B (Code 085)',
      'Sanskrit (Code 122)',
      'Urdu (Code 003)',
      'Punjabi (Code 004)',
      'Information Technology (Code 402)',
      'Artificial Intelligence (Code 417)',
      'Computer Applications (Code 165)',
      'NCC',
      'Art Education',
      'PEWB',
      'Health and Physical Education',
    ],
  },
  {
    id: 'C10',
    name: 'Class 10',
    availableSubjects: [
      'Mathematics Standard (Code 041)',
      'Mathematics Basic (Code 241)',
      'Science (Code 086)',
      'Social Science (Code 087)',
      'English Language and Literature (Code 184)',
      'English Communicative (Code 101)',
      'Hindi Course A (Code 002)',
      'Hindi Course B (Code 085)',
      'Sanskrit (Code 122)',
      'Urdu (Code 003)',
      'Punjabi (Code 004)',
      'Information Technology (Code 402)',
      'Artificial Intelligence (Code 417)',
      'Computer Applications (Code 165)',
      'NCC',
      'Art Education',
      'PEWB',
      'Health and Physical Education',
    ],
  },
  {
    id: 'C11_SCI',
    name: 'Class 11 (Science)',
    availableSubjects: [
      'English Core (Code 301)',
      'Physics (Code 042)',
      'Chemistry (Code 043)',
      'Mathematics (Code 041)',
      'Biology (Code 044)',
      'Computer Science (Code 083)',
      'Informatics Practices (Code 065)',
      'Physical Education (Code 048)',
    ],
  },
  {
    id: 'C11_COM',
    name: 'Class 11 (Commerce)',
    availableSubjects: [
      'English Core (Code 301)',
      'Accountancy (Code 055)',
      'Business Studies (Code 054)',
      'Economics (Code 030)',
      'Applied Mathematics (Code 241)',
      'Informatics Practices (Code 065)',
      'Physical Education (Code 048)',
    ],
  },
  {
    id: 'C11_HUM',
    name: 'Class 11 (Humanities)',
    availableSubjects: [
      'English Core (Code 301)',
      'History (Code 027)',
      'Political Science (Code 028)',
      'Geography (Code 029)',
      'Economics (Code 030)',
      'Psychology (Code 037)',
      'Physical Education (Code 048)',
    ],
  },
  {
    id: 'C12_SCI',
    name: 'Class 12 (Science)',
    availableSubjects: [
      'English Core (Code 301)',
      'Physics (Code 042)',
      'Chemistry (Code 043)',
      'Mathematics (Code 041)',
      'Biology (Code 044)',
      'Computer Science (Code 083)',
      'Informatics Practices (Code 065)',
      'Physical Education (Code 048)',
    ],
  },
  {
    id: 'C12_COM',
    name: 'Class 12 (Commerce)',
    availableSubjects: [
      'English Core (Code 301)',
      'Accountancy (Code 055)',
      'Business Studies (Code 054)',
      'Economics (Code 030)',
      'Applied Mathematics (Code 241)',
      'Informatics Practices (Code 065)',
      'Physical Education (Code 048)',
    ],
  },
  {
    id: 'C12_HUM',
    name: 'Class 12 (Humanities)',
    availableSubjects: [
      'English Core (Code 301)',
      'History (Code 027)',
      'Political Science (Code 028)',
      'Geography (Code 029)',
      'Economics (Code 030)',
      'Psychology (Code 037)',
      'Physical Education (Code 048)',
    ],
  },
];
